name: "Build Application Firewall"
description: "Governance, Risk and Compliance for the Software Supply Chain."
inputs:
  github-token:
    description: "github token"
    required: true
branding:
  icon: bell
  color: green
runs:
  using: "node16"
  main: "dist/index.js"
  post: "cleanup/index.js"
