name: Update Latest Tag

on:
  release:
    types: [published, edited]

jobs:
  update-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Update latest tag
        uses: EndBug/latest-tag@latest
        with:
          # Optional: customize the tag name (default is 'latest')
          tag-name: latest
          # Optional: add a description
          description: Latest stable release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
